### ISSUE TITLE
Crash shortly after loading into a World

### ISSUE THREAD

**Issue by Enderborn1235** [Mindoth/ancientmagicks#1]
[crash-2024-11-18_13.11.23-server.txt](https://github.com/user-attachments/files/17805221/crash-2024-11-18_13.11.23-server.txt)

**Comment by Mindoth** [comment]
Thanks for letting me know. I don't seem to be able to replicate this but based on your crash log I have a pretty good idea what's causing it. I'll push out an update but keep this issue open until I'm sure it's gone so feel free to let me know if this still happens in the newest update (0.2.4).

**Comment by Enderborn1235** [comment]
That seems to have done it! Thank you so much!
